-- MySQL Script generated by MySQL Workbench
-- Mon Apr 11 23:58:03 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ACMESummit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ACMESummit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ACMESummit` DEFAULT CHARACTER SET utf8 ;
USE `ACMESummit` ;

-- -----------------------------------------------------
-- Table `ACMESummit`.`Registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACMESummit`.`Registration` (
  `ConfirmationNumber` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `CompanyName` VARCHAR(100) NOT NULL,
  `Title` VARCHAR(60) NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `StreetAddress` VARCHAR(100) NOT NULL,
  `City` VARCHAR(30) NOT NULL,
  `Province` VARCHAR(30) NOT NULL,
  `ZipCode` VARCHAR(10) NOT NULL,
  `Country` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`ConfirmationNumber`),
  UNIQUE INDEX `ConfirmationNumber_UNIQUE` (`ConfirmationNumber` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  UNIQUE INDEX `PhoneNumber_UNIQUE` (`PhoneNumber` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ALTER TABLE Registration AUTO_INCREMENT = 153894;